"""
Django settings for woox_travel project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""




from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@y07l^^r6ufw+o(0glak!&%j%9(g3=0dyzwj!#+nn3!oz8@ulh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # only once
    'django.contrib.admin',  # only once
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My custom apps
    'best_offers_about',
    'best_offers_deals',
    'cities_towns_about',
    'news',
    'paginator',
    'payment',
    'register',
    'service',
    'user_reservations',
    'visit_places_home',
    'tinymce',
]


JAZZMIN_SETTINGS = {
    "welcome_sign": "Welcome🚀",
    "show_ui_builder": False,
    # "show_ui_builder": True,  #just comment out and see user 50% left blank error 
    # "login_logo": "static/assets/images/logo.png",
}

#theme customization
# JAZZMIN_UI_TWEAKS = {
#     # "theme": "darkly",  #with white background
#     # "theme": "superhero",  # ok 
#     # "theme": "solar",  #proper blue
#     # "theme": "slate",  # very low
#     # "theme": "cyborg",  # good
#     # "theme": "cosmo",  #best
#     "theme": "pulse",  #best
#     "default_theme_mode": "dark", #ok dark option
# }

#for authentication

AUTHENTICATION_BACKENDS=[
    'django.contrib.auth.backends.ModelBackend'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'woox_travel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #to import template folder
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'woox_travel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


# 'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#to import static folder

STATICFILES_DIRS = [
    BASE_DIR,"static"
]

#to import media folder

MEDIA_ROOT = BASE_DIR/'media'

MEDIA_URL = '/media/'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'calmcoder2025@gmail.com'
EMAIL_HOST_PASSWORD = 'utrj qklo sqpf urny'  # Gmail App Password
EMAIL_USE_TLS = True

# AUTH_USER_MODEL = 'register.UserType'