# Generated by Django 5.0.4 on 2024-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestOffersAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boa_img', models.FileField(max_length=200, upload_to='best_offers_about/')),
                ('boa_city_name', models.CharField(max_length=50)),
                ('boa_check_ins', models.IntegerField(max_length=10)),
                ('boa_price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
