# Generated by Django 5.0.4 on 2024-06-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_offers_about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestoffersabout',
            name='boa_check_ins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bestoffersabout',
            name='boa_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
