# Generated by Django 5.0.4 on 2024-06-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_offers_about', '0002_alter_bestoffersabout_boa_check_ins_and_more'),
    ]

    operations = [
        migrations.AddField(
        model_name='bestoffersabout',
        name='boa_tour_duratrions',
        field=models.CharField(default='1 Day', max_length=100),
        ),
    ]
