# Generated by Django 5.0.4 on 2024-06-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_offers_about', '0003_bestoffersabout_boa_tour_duratrions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestoffersabout',
            name='boa_tour_duratrions',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
