# Generated by Django 5.0.4 on 2024-06-09 18:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('best_offers_about', '0004_alter_bestoffersabout_boa_tour_duratrions'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestoffersabout',
            name='boa_tour_description',
            field=tinymce.models.HTMLField(default='hello'),
        ),
    ]
