# Generated by Django 5.0.4 on 2024-06-11 13:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('best_offers_about', '0006_alter_bestoffersabout_boa_tour_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestoffersabout',
            name='boa_tour_description',
            field=tinymce.models.HTMLField(default='hello'),
        ),
    ]
