# Generated by Django 5.0.4 on 2024-06-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_guest', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
