# Generated by Django 5.0.4 on 2024-06-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateField(default=None),
        ),
    ]
