# Generated by Django 5.0.4 on 2024-06-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reservations', '0002_reservation_check_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateField(),
        ),
    ]
