# Generated by Django 5.0.4 on 2024-06-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reservations', '0003_alter_reservation_check_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tour_description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tour_duration',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
