# Generated by Django 5.0.4 on 2024-06-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reservations', '0004_reservation_tour_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in_date',
            field=models.CharField(max_length=15),
        ),
    ]
