# Generated by Django 5.0.4 on 2024-06-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reservations', '0005_alter_reservation_check_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
