# Generated by Django 5.0.4 on 2024-06-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(editable=False, max_length=10)),
                ('reservation_user_id', models.IntegerField(editable=False)),
                ('payment_id', models.CharField(blank=True, editable=False, max_length=5, unique=True)),
                ('username', models.CharField(editable=False, max_length=50)),
                ('user_destination', models.CharField(editable=False, max_length=50)),
                ('user_total_payment', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('user_pay_method', models.CharField(editable=False, max_length=10)),
                ('user_card_num', models.IntegerField(editable=False)),
                ('user_card_exp_date', models.DateField(editable=False)),
                ('user_card_cvv', models.IntegerField(editable=False)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
