# Generated by Django 5.0.4 on 2024-06-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='user_card_cvv',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='user_card_exp_date',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='user_card_num',
        ),
    ]
