# Generated by Django 5.0.4 on 2024-06-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_userpayment_user_card_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='user_invoice',
            field=models.FileField(default=None, max_length=200, upload_to='invoice/'),
        ),
    ]
