# Generated by Django 5.0.4 on 2024-06-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_userpayment_user_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='payment_time',
            field=models.DateTimeField(editable=False),
        ),
    ]
