# Generated by Django 5.0.4 on 2024-06-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCityTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_img', models.FileField(max_length=200, upload_to='about_cities_towns/')),
                ('act_city_name', models.CharField(max_length=50)),
            ],
        ),
    ]
