# Generated by Django 5.0.4 on 2024-06-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_towns_about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcitytown',
            name='act_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
