# Generated by Django 5.0.4 on 2024-06-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_towns_about', '0002_aboutcitytown_act_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcitytown',
            name='act_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
