# Generated by Django 5.0.4 on 2024-06-09 18:06

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_towns_about', '0003_alter_aboutcitytown_act_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcitytown',
            name='act_tour_description',
            field=tinymce.models.HTMLField(default='hello'),
        ),
        migrations.AddField(
            model_name='aboutcitytown',
            name='act_tour_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
