# Generated by Django 5.0.4 on 2024-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_towns_about', '0004_aboutcitytown_act_tour_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcitytown',
            name='act_tour_description',
            field=models.TextField(default='hello'),
        ),
    ]
