# Generated by Django 5.0.4 on 2024-06-11 13:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_towns_about', '0005_alter_aboutcitytown_act_tour_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcitytown',
            name='act_tour_description',
            field=tinymce.models.HTMLField(default='hello'),
        ),
    ]
