# Generated by Django 6.0.3 on 2026-03-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_towns_about', '0006_alter_aboutcitytown_act_tour_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcitytown',
            name='act_img2',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='about_cities_towns/'),
        ),
        migrations.AddField(
            model_name='aboutcitytown',
            name='act_img3',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='about_cities_towns/'),
        ),
        migrations.AddField(
            model_name='aboutcitytown',
            name='act_img4',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='about_cities_towns/'),
        ),
        migrations.AddField(
            model_name='aboutcitytown',
            name='act_img5',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='about_cities_towns/'),
        ),
    ]
