# Generated by Django 6.0.3 on 2026-03-26 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_towns_about', '0007_aboutcitytown_act_img2_aboutcitytown_act_img3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('place_image', models.ImageField(upload_to='city_places/')),
                ('place_description', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='cities_towns_about.aboutcitytown')),
            ],
        ),
    ]
