# Generated by Django 5.0.4 on 2024-05-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginator',
            name='paginator_slug',
        ),
    ]
