# Generated by Django 5.0.4 on 2024-06-05 18:45

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestOfferDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bod_img', models.FileField(max_length=200, upload_to='best_offers_deals/')),
                ('bod_offer', models.CharField(max_length=50)),
                ('bod_city_name', models.CharField(max_length=50)),
                ('bod_tour_duration', models.CharField(max_length=50)),
                ('bod_des', tinymce.models.HTMLField()),
            ],
        ),
    ]
