# Generated by Django 5.0.4 on 2024-06-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_offers_deals', '0002_alter_bestofferdeals_bod_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestofferdeals',
            name='bod_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
