# Generated by Django 5.0.4 on 2024-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_offers_deals', '0003_bestofferdeals_bod_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestofferdeals',
            name='bod_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
