# Generated by Django 5.0.4 on 2024-06-09 18:14

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('best_offers_deals', '0004_alter_bestofferdeals_bod_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestofferdeals',
            name='bod_tour_description',
            field=tinymce.models.HTMLField(default='hello'),
        ),
    ]
