# Generated by Django 5.0.4 on 2024-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_offers_deals', '0005_bestofferdeals_bod_tour_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestofferdeals',
            name='bod_tour_description',
            field=models.TextField(default='hello'),
        ),
    ]
