# Generated by Django 5.0.4 on 2024-05-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phone',
            new_name='username',
        ),
    ]
