# Generated by Django 5.0.4 on 2024-06-04 17:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPlaceHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vph_img', models.FileField(max_length=200, upload_to='visit_place_home/')),
                ('vph_place', models.CharField(max_length=50)),
                ('vph_country', models.CharField(max_length=50)),
                ('vph_des', tinymce.models.HTMLField()),
                ('vph_people', models.IntegerField(max_length=10)),
                ('vph_km', models.IntegerField(max_length=10)),
                ('vph_price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
