# Generated by Django 5.0.4 on 2024-06-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_places_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitplacehome',
            name='vph_km',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitplacehome',
            name='vph_people',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitplacehome',
            name='vph_price',
            field=models.FloatField(max_length=10),
        ),
    ]
